export const videoTypes = [
  "MOVIE",
  "DEFAULT",
  "SORTMOVIE",
  "SINGLEVIDEO",
  "DIAMOND",
  "PREMIUM",
  "UPCOMMING",
  "STANDARD",
  "TRAILER",
  "WEBSERIES",
];
export const planTypes = [
  "GOLD",
  "THREEMONTHS",
  "ONEYEAR",
  "DIAMOND",
  "SIXMONTHS",
  "ONEDAY",
  "ONEMONTH",
  "PRIMIUM",
  "STANDARD",
  "BASIC",
];

export const languages = [
  "Hindi",
  "Marathi",
  "Haryanvi",
  "Bengali",
  "Punjabi",
  "Assamese",
  "Rajasthani",
  "Bhojpuri",
  "Oriya",
  "Nepali",
  "Gadhwali",
  "Kashmiri",
  "Chhattisgarhi",
  "Manipuri",
  "English",
  "Malyalam",
  "Tamil",
  "Telugu ",
  "Kannad",
  "Hyderabadi",
  "Gujarati",
];
export const genres = [
  "Drama",
  "Comedy",
  "Horror",
  "Thriller",
  "Social",
  "Romantic",
  "Action",
  "Suspense",
  "Motivational",
  "Devotional",
  "Edutainment",
  "Infotainment",
  "Docutainment",
  "Historical",
  "Fantasy",
  "Mythology",
  "Bhakti song",
  "Romantic song",
  "Sad song",
  "Horror song ",
  "Folk song",
  "Rap song",
  "Item song",
  "Classical song",
];
export const cbfcrating = ["U", "U/A", "A"];
